### ISSUE TITLE
CF-1 Реализовать создание Сотрудников

### ISSUE THREAD

**Issue by Sharykhin** [MyskinD/chocolate-factory#1]
Создать АПИ для создания сотрудников (Stuff)
```bash
POST /stuffs
```

своства:
1. first name - string required max 50 characters
2. last name string required max 50 characters
3. email string required valid email unique
4. password string required min 8

Пример тела запроса:
 ```json
{
    "first_name": "Dmitry",
    "last_name": "Teteruk",
    "email": "hui@vpesok.horosho",
    "password": "11111111"
}
```
в ответ возвращать созданную сущность. Пример ответа (пароль не возращать)
```json
"stuff": {
    "id": 1,
    "first_name": "Dmitry",
    "last_name": "Teteruk",
    "email": "hui@vpesok.horosho"
},
"meta": {
    "version": "1.0"
}
```

**Общие замечания:**
Помимо броузера система будет использоваться мобильными приложениями, поэтому нужно предусмотреть версионность нашего АПИ, к примеру через урл /v1/stuffs или через заголовок

**Comment by MyskinD** [comment]
оно и здесь появлиось! ты как это сделал?

чт, 9 янв. 2020 г. в 23:00, Sergey <notifications@github.com>:
